- name: Post Infrastructure
  hosts: localhost
  vars_files:
    - "./env_vars.yml"
  become: false
  tasks:
    - name: Migrate Kube file 
      script: files/kube.sh

- name: Create Persistent Volumes
  hosts: nfs
  tasks:  
    - name: Create PVs
      script: ./files/pv.sh

- hosts: localhost
  vars_files:
    - "./env_vars.yml"
  become: false
  tasks:
    - name: Claim PVs
      script: files/userpvs.sh
     
    - name: Multitenancy Requirements
      script: ./files/multitenancy.sh

