- name: Post Infrastructure
  hosts: localhost
  vars_files:
    - "./env_vars.yml"
  become: false
  tasks:
    - script: files/kube.sh

- name: Create Persistent Volumes
  hosts: nfs
  tasks:  
    - name: Create PVs
      script: ./files/pv.sh

- hosts: localhost
  vars_files:
    - "./env_vars.yml"
  become: false
  tasks:
    - name: Claim PVs
      command: files/userpvs.sh
      args:
        executable: /bin/bash
    - name: Enviroment Configuration - NetworkPolicy is configured and working with projects isolated by default
      command: files/networkpolicy.sh
      args:
        executable: /bin/bash
    - name: Multitenancy Requirements
      command: files/multitenancy.sh
      args:
        executable: /bin/bash


