- name: Set GUID for all hosts
  hosts: all
  tasks:
    - name: All GUID env variable
      shell: export GUID=`hostname | cut -d"." -f2`; echo "export GUID=$GUID" >> $HOME/.bashrc

- name: Check docker's status is active
  hosts: nodes
  tasks:
    - name: docker restart
      shell: systemctl status docker | grep Active

- name: Check NFS are shared
  hosts: nfs
  tasks:
    - name: Check NFS are shared
      shell: exportfs

- name: Install openshift client
  hosts: localhost
  tasks:
    - name: Install packages
      yum:
        name:
          - atomic-openshift-utils
          - atomic-openshift-clients
        state: present

- name: Build inventory file 
  hosts: localhost
  connection: local
  become: true
  vars_files:
    - "./env_vars.yml"
  tasks:
    - name: Copy inventory file to /etc/ansible/hosts
      copy:
        src: /root/OpenShift-BootCamp-HW/ocp-ha-lab/files/hosts
        dest: /etc/ansible/hosts
        force: yes
    - replace:
        path: /etc/ansible/hosts
        regexp: "[$]GUID"
        replace: "{{ guid }}"
        backup: yes
    

