- name: Step 002 Post Infrastructure
  hosts: localhost
  connection: local
  vars_files:
    - "./env_vars.yml"
  become: false
  tasks:
    - name: Get Kube File
    - script: files/kube.sh
    - name: Create persistent volumes
    - script: files/pv.sh
      run_once: true
      delegate_to: support1.{{ guid }}.internal