- name: Step 002 Post Infrastructure
  hosts: localhost
  connection: local
  vars_files:
    - "./env_vars.yml"
  become: false
  tasks:
    - name: Create persistent volumes
      script: files/pv.sh