- name: Step 002 Post Infrastructure
  hosts: localhost
  vars_files:
    - "./env_vars.yml"
  become: false
  tasks:
    - script: files/kube.sh
- hosts: support1.{{guid}}.internal
  connection: local
  become: true
  tasks:  
    - copy:
        src: /root/OpenShift-BootCamp-HW/files/ocp-ha-lab/files/pv.sh
        dest: /root/pv.sh
    - name: Start application
      command: bash /root/pv.sh
      args:
        chdir: "/root"
        executable: /bin/bash
