- name: Step 002 Post Infrastructure
  hosts: localhost
  vars_files:
    - "./env_vars.yml"
  become: false
  tasks:
    - script: files/kube.sh
- hosts: support1.{{guid}}.internal
  become: true
  tasks:  
    - name: Transfer file from ServerA to ServerB
      synchronize:
        src: /root/OpenShift-BootCamp-HW/files/ocp-ha-lab/files/pv.sh
        dest: /root/pv.sh
      delegate_to: localhost
    - name: Start application
      command: ./pv.sh
      args:
        executable: /bin/bash
