- name: Step 000 Pre Infrastructure
  hosts: localhost
  connection: local
  become: false
  vars_files:
    - "./env_vars.yml"
  tags:
    - step000
    - pre_infrastructure
  tasks:
    - debug:
        msg: "Step 000 Pre Infrastructure - Copying inventory file to /etc/ansible/hosts"
    - debug:
        msg: "hi {{ guid }}"
    - copy:
        src: /root/OpenShift-BootCamp-HW/files/ocp-ha-lab/files/hosts
        dest: /etc/ansible/hosts
        force: yes
    - replace:
        path: /etc/ansible/hosts
        regexp: "[$]GUID"
        replace: "{{ guid }}"
        backup: yes

